const SAMPLE_SERVER_BASE_URL = 'YOUR_SERVER_BASE_URL';
// const SAMPLE_SERVER_BASE_URL = 'http://localhost:3000';

const API_KEY = 'API_KEY';
const SESSION_ID = 'SESSION_ID';
const TOKEN = 'TOKEN';
const PROVIDER_TOKEN = 'PROVIDER_TOKEN';

export {
  SAMPLE_SERVER_BASE_URL,
  API_KEY,
  SESSION_ID,
  TOKEN,
  PROVIDER_TOKEN
};
