const SAMPLE_SERVER_BASE_URL = 'YOUR_SERVER_BASE_URL';
const API_KEY = 'API_KEY';
const SESSION_ID = 'SESSION_ID';
const TOKEN = 'TOKEN';
const PROVIDER_TOKEN = 'PROVIDER_TOKEN';
const SUBSCRIBER_TOKEN_A = 'SUBSCRIBER_TOKEN_A';
const SUBSCRIBER_TOKEN_B = 'SUBSCRIBER_TOKEN_B';

export {
	SAMPLE_SERVER_BASE_URL,
	API_KEY,
	SESSION_ID,
	TOKEN,
	PROVIDER_TOKEN,
	SUBSCRIBER_TOKEN_A,
	SUBSCRIBER_TOKEN_B
};
