// const SAMPLE_SERVER_BASE_URL = 'YOUR_SERVER_BASE_URL';
const SAMPLE_SERVER_BASE_URL = 'http://localhost:3000';

// const API_KEY = 'API_KEY';
// const SESSION_ID = 'SESSION_ID';
// const TOKEN = 'TOKEN';
// const PROVIDER_TOKEN = 'PROVIDER_TOKEN';

const API_KEY = '46409352';
const SESSION_ID = '2_MX40NjQwOTM1Mn5-MTU2NzA5MTk5MjAxMX50WDR0eG8zM2RWK0lvQkljK0dYNnViT1F-fg';
const TOKEN = 'T1==cGFydG5lcl9pZD00NjQwOTM1MiZzaWc9ZjYxMjgxMTExZmQ0MjQ2NDRhYzBkMTVmYTQ3NmVlZmYwODZmMWVkNDpzZXNzaW9uX2lkPTJfTVg0ME5qUXdPVE0xTW41LU1UVTJOekE1TVRrNU1qQXhNWDUwV0RSMGVHOHpNMlJXSzBsdlFrbGpLMGRZTm5WaVQxRi1mZyZjcmVhdGVfdGltZT0xNTY3MDkyMDA0Jm5vbmNlPTAuNDU0NTI4NDIwNDA2MjczNiZyb2xlPXB1Ymxpc2hlciZleHBpcmVfdGltZT0xNTY5Njg0MDA0JmluaXRpYWxfbGF5b3V0X2NsYXNzX2xpc3Q9';
const PROVIDER_TOKEN = 'T1==cGFydG5lcl9pZD00NjQwOTM1MiZzaWc9YTE4ZjFjNDZiNGFkYmI5ZjM2MWU4MGMxOWM4OGMwMWYwYzdkNmFlNTpzZXNzaW9uX2lkPTJfTVg0ME5qUXdPVE0xTW41LU1UVTJOekE1TVRrNU1qQXhNWDUwV0RSMGVHOHpNMlJXSzBsdlFrbGpLMGRZTm5WaVQxRi1mZyZjcmVhdGVfdGltZT0xNTY3MDkyMzY1Jm5vbmNlPTAuNTQ3NDQ1NTY2MDgzMjMmcm9sZT1wdWJsaXNoZXImZXhwaXJlX3RpbWU9MTU2OTY4NDM2NCZpbml0aWFsX2xheW91dF9jbGFzc19saXN0PQ==';

export {
  SAMPLE_SERVER_BASE_URL,
  API_KEY,
  SESSION_ID,
  TOKEN,
  PROVIDER_TOKEN
};
